第4章の章末演習問題

### [1] 携帯電話やデジタルカメラで、赤、青、緑の物体の写真を何枚か撮りましょう（カメラがない場合は、インターネットからダウンロードすることもできます）。
※ ここではGoogle Colaraboratoryでの実行を想定しています。


In [ ]:
※本フォルダに、無料写真素材　写真AC（商用利用可）のデータを配置しています。

apple.jpg、sky.jpg、forest.jpg


https://www.photo-ac.com/main/detail/345453?title=%E3%83%AA%E3%83%B3%E3%82%B4&searchId=68658080

https://www.photo-ac.com/main/detail/3343123?title=%E3%81%99%E3%81%A3%E3%81%8D%E3%82%8A%E6%99%B4%E3%82%8C%E3%82%84%E3%81%8B%E3%81%AA%E5%A4%8F%E3%81%AE%E7%A9%BA&searchId=68660407

https://www.photo-ac.com/main/detail/3518379?title=%E6%A8%B9%E6%9C%A8_%E6%A3%AE%E6%9E%97_3&searchId=68662146



In [ ]:
#### （a）各画像を読み込み、テンソルに変換してください。

In [1]:
# 回答
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)

In [3]:
import imageio

In [5]:
img_arr_r = imageio.imread('../data/p1ch4/red.jpg')
img_arr_g = imageio.imread('../data/p1ch4/green.jpg')
img_arr_b = imageio.imread('../data/p1ch4/blue.jpg')
img_arr_r.shape, img_arr_g.shape, img_arr_b.shape

((2336, 4160, 3), (4160, 2336, 3), (3120, 4160, 3))

In [11]:
img_r = torch.from_numpy(img_arr_r)
img_g = torch.from_numpy(img_arr_g)
img_b = torch.from_numpy(img_arr_b)

TypeError: from_numpy() takes no keyword arguments

In [13]:
img_r_f = img_r.to(dtype=torch.float)
img_g_f = img_g.to(dtype=torch.float)
img_b_f = img_b.to(dtype=torch.float)

In [14]:
out_r = img_r_f.permute(2, 0, 1)
out_g = img_g_f.permute(2, 0, 1)
out_b = img_b_f.permute(2, 0, 1)
out_r.shape, out_g.shape, out_b.shape

(torch.Size([3, 2336, 4160]),
 torch.Size([3, 4160, 2336]),
 torch.Size([3, 3120, 4160]))

In [15]:
out_r.dtype

torch.float32

In [ ]:
#### (b）各画像テンソルについて、.mean()メソッドを使用して、画像の明るさを求めてください。

In [18]:
# 回答 dim=1で次元1で平均する
torch.mean(out_r, dim=1), torch.mean(out_g, dim=1), torch.mean(out_b, dim=1)

(tensor([[ 79.6667,  78.6667,  ...,  76.0000,  76.0000],
         [ 76.6667,  75.6667,  ...,  74.0000,  76.0000],
         ...,
         [186.0000, 185.0000,  ...,  42.0000,  41.0000],
         [184.0000, 184.0000,  ...,  44.0000,  43.0000]]),
 tensor([[124.0000, 125.0000,  ..., 137.3333, 133.3333],
         [127.0000, 126.0000,  ..., 131.3333, 140.3333],
         ...,
         [ 92.0000,  93.0000,  ..., 150.0000, 155.0000],
         [ 94.0000,  88.0000,  ..., 147.0000, 149.3333]]),
 tensor([[145.3333, 145.3333,  ..., 113.0000, 113.0000],
         [141.3333, 143.3333,  ..., 112.0000, 113.0000],
         ...,
         [173.6667, 169.6667,  ..., 210.6667, 211.6667],
         [170.6667, 167.6667,  ..., 211.6667, 212.6667]]))

In [23]:
# 次元1が平均されたことで次元が減ったことの確認
out_r.shape, torch.mean(out_r, dim=1).shape

(torch.Size([3, 2336, 4160]), torch.Size([3, 4160]))

#### （c）各画像の各チャンネルの平均を取ってください。求めたチャンネルの平均値だけから、赤、緑、青の物体を識別できるか確認してください。

In [19]:
# さらに、次元1，2で平均する　平均対象の次元を逐次的に指定する
# 回答 赤
torch.mean(out_r, dim=1).mean(dim=1)

(tensor([132.3350, 109.1540, 109.0145]),)

In [20]:
# 回答 緑
torch.mean(out_g, dim=1).mean(dim=1)

tensor([143.6180, 157.2123, 145.9531])

In [21]:
# 回答 青
torch.mean(out_b, dim=1).mean(dim=1)

tensor([125.8333, 124.3068, 106.6931])

### [2] Pythonのソースコードを含む比較的大きなファイルを用意してください。

※https://github.com/YutaroOgawa/pytorch_advanced/blob/master/1_image_classification/utils/dataloader_image_classification.py

をフォルダ内に用意しています。


#### （a）ソースファイル内のすべての単語のインデックスを作成してください (トークン化はシンプルにしても複雑にしても構いません。 最初は正規表現r"[^a-zA-Z0-9_]+"とスペースで、単語を一度置き換えることをおすすめします)。

In [25]:
# 回答
with open('./data_loader.py', encoding='utf8') as f:
    text = f.read()

In [26]:
# 正規表現で抽出 以下のURLを参考
# https://techacademy.jp/magazine/19307
import re
words_in_file = re.findall(r"[a-zA-Z0-9_]+", text) # 文字と数字

print(words_in_file)

['import', 'glob', 'import', 'os', 'path', 'as', 'osp', 'import', 'torch', 'utils', 'data', 'as', 'data', 'from', 'torchvision', 'import', 'models', 'transforms', 'from', 'PIL', 'import', 'Image', 'class', 'ImageTransform', 'RandomResizedCrop', 'RandomHorizontalFlip', 'Attributes', 'resize', 'int', 'mean', 'R', 'G', 'B', 'std', 'R', 'G', 'B', 'def', '__init__', 'self', 'resize', 'mean', 'std', 'self', 'data_transform', 'train', 'transforms', 'Compose', 'transforms', 'RandomResizedCrop', 'resize', 'scale', '0', '5', '1', '0', 'transforms', 'RandomHorizontalFlip', 'transforms', 'ToTensor', 'transforms', 'Normalize', 'mean', 'std', 'val', 'transforms', 'Compose', 'transforms', 'Resize', 'resize', 'transforms', 'CenterCrop', 'resize', 'resize', 'resize', 'transforms', 'ToTensor', 'transforms', 'Normalize', 'mean', 'std', 'def', '__call__', 'self', 'img', 'phase', 'train', 'Parameters', 'phase', 'train', 'or', 'val', 'return', 'self', 'data_transform', 'phase', 'img', 'def', 'make_datapath_

#### （b）本章の「高慢と偏見」で作ったインデックスと比較してみてください。どちらの方がサイズは大きいですか？

In [28]:
# 回答
len(words_in_file)

230

In [30]:
# 重複を消し、並び替える
word_list = list(set(words_in_file)) # setで同一語を1つにする= 重複排除
word_list = sorted(word_list)
len(word_list)

90

In [31]:
word2index_dict = {word: i for (i, word) in enumerate(word_list)}

len(word2index_dict), word2index_dict['transform']

(90, 86)

#### （c）ソースコードファイルのワンホットエンコーディングを作成してください。

In [ ]:
# 回答

#### （d）今回のエンコーディングで失われる情報は何でしょうか？本章での「高慢と偏見」のエンコーディングで失われた情報と比較してみてください。

In [ ]:
# 回答
# 単語の並び、単語間の関係、回数など

In [ ]:
#　省略

以上。
